### ISSUE TITLE
Implement scan_db and db_next

### ISSUE THREAD

**Issue by Cashmaney** [scrtlabs/SecretNetwork#275]

**Comment by reuvenpo** [comment]
(We're several months into mainnet today)
`scan_db` and `db_next` can not be implemented in the same way they are in the original cosmwasm.
The way they work is that they rely on the fact that tendermint's storage is a prefix tree. This is irrelevant in our case since the tendermint storage is encrypted.
We can work around this by adding a "HashMap" abstraction over the storage to [`secret-toolkit`](https://github.com/enigmampc/secret-toolkit)
