### ISSUE TITLE
Binary of Secretcli is... secretd.

### ISSUE THREAD

**Issue by Subfortytwo** [scrtlabs/SecretNetwork#851]
Hi, I am trying to follow this tutorial: https://build.scrt.network/light-client-mainnet.html

```
$ wget https://github.com/scrtlabs/SecretNetwork/releases/download/v1.2.1/secretcli-linux-amd64
$ chmod  +x secretcli-linux-amd64
$ ./secretcli-linux-amd64 | head -n 4
The Secret Network App Daemon (server)

Usage:
  secretd [command]
```

I am expecting it to be secretcli.

Thank you :)

**Comment by toml01** [comment]
Since v1.2.0 (cosmos sdk v0.44) there is no `cli` agent, only a `secretd` (which has all the `cli` capabilities).
We compiled a `secretcli` version, which is in practice just a `secretd` without the requirement for SGX, so anyone could use it without expensive hardware.

I took note that we need to change the help comments :) Thanks
